puts "The student of my cohort at Makers Academy"
puts "---------------------------------"
puts "Arin Hanson"
puts "Stan Smith"
puts "Dan Evidan"
puts "Rick Grimes"
puts "Clint Eastwood"
puts "Charlie Sheen"
puts "Gavin Free"
puts "Michael Jones"
puts "Ed O'Brien"